
# Inside the screen session, start an interactive session
srun --partition=gpu_a100 --gres=gpu:1 --job-name=bash --ntasks=1 --cpus-per-task=12 --time=03:00:00 --pty bash

export OPENAI_API_KEY="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"

module purge
module load 2023
module load Anaconda3/2023.07-2
source activate RACDH